version: '3.9'
services:
  app-service:
    container_name: voucher-service
    image: osamamosaad/voucher-service:1.0.0
    build:
      context: .
    ports:
      - ${VOUCHER_SERVICE_PORT}:3000
    depends_on:
      - db
      - redis
    networks:
      net_range:
        ipv4_address: ${VOUCHER_SERVICE_IP}

  db:
    container_name: db-voucher
    hostname: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: no
      MYSQL_DATABASE: voucher_pool
    ports:
      - 33064:3306
    volumes:
      - mysqlDB:/var/lib/mysql:delegated
    networks:
      net_range:
        ipv4_address: ${DATABASE_HOST}

  redis:
    image: redis
    networks:
      net_range:
        ipv4_address: ${REDIS_HOST}

volumes:
  mysqlDB:

networks:
  net_range:
    ipam:
      driver: default
      config:
        - subnet: 172.14.0.0/24
